export { CustomerUpload as CustomerUploadDesigner } from './CustomerUpload/designer'
export { DescriptionTextArea as DescriptionTextAreaDesigner } from './DescriptionTextArea/designer'
export { DisplayNameInput as DisplayNameInputDesigner } from './DisplayNameInput/designer'
export { IconPicker as IconPickerDesigner } from './IconPicker/designer'
export { IDInput as IDInputDesigner } from './IDInput/designer'
export { AtaliList as AtaliListDesigner } from './AtaliList/designer'
export { MenuTree as MenuTreeDesigner } from './MenuTree/designer'
export { MetadataSelect as MetadataSelectDesigner } from './MetadataSelect/designer'
export { AtaliMonacoInput as MonacoInputDesigner } from './MonacoInput'
export { NameInput as NameInputDesigner } from './NameInput'
export { RoleSelect as RoleSelectDesigner } from './RoleSelect'
export { TagSelect as TagSelectDesigner } from './TagSelect'
export { UserSelect as UserSelectDesigner } from './UserSelect'
export { RelatedPageInput as RelatedPageInputDesinger } from './RelatedPageInput/designer';
export { AudioRecorder } from './AtaliAudioRecorder/designer'
export { AtaliAudio } from './AtaliAudio/designer'